#index:
#    path: /
#    controller: App\Controller\DefaultController::index

app_lucky_number:
    path: /lucky/number
    controller: App\Controller\LuckyController::number

app_browse:
    path: /browse
    controller: App\Controller\BrowseController::getRestaurants